#!/usr/bin/env python3
"""
Print the actual task generated by Gemini from our earlier test
"""

import json
from printer_service import PrinterService

def main():
    """Load and print the real task we generated earlier"""
    print("🎯 Printing the real mission briefing from Gemini analysis...")
    
    # Load the analysis we saved earlier
    try:
        with open('last_analysis.json', 'r') as f:
            data = json.load(f)
            analysis = data['analysis']
            email_data = data['email']
        
        print(f"📧 Original Email: {email_data['subject']}")
        print(f"🤖 AI Analysis: {analysis['mission_briefing']['title']}")
        print(f"⚡ Urgency: {analysis['mission_briefing']['urgency']}")
        
    except FileNotFoundError:
        print("❌ No previous analysis found. Run gemini_test.py first to generate a task.")
        return
    except Exception as e:
        print(f"❌ Error loading analysis: {e}")
        return
    
    # Initialize printer (will fall back to file if USB doesn't work)
    printer = PrinterService(fallback_to_file=True)
    
    print(f"🖨️  Printer Status: {printer.get_printer_info()}")
    
    # Print the real mission briefing
    success = printer.print_mission(analysis, "Agent Roshin")
    
    if success:
        print("🎉 Real mission briefing printed successfully!")
        print("   If using file mode, check printed_missions.txt")
        
        # Also save formatted text for viewing
        briefing_text = printer.format_mission_briefing(analysis, "Agent Roshin")
        with open('formatted_briefing.txt', 'w') as f:
            f.write(briefing_text)
        print("   📄 Formatted briefing saved to formatted_briefing.txt")
    
    printer.close()

if __name__ == '__main__':
    main()